server:
  port: 80

pagehelper:
  helper-dialect: mysql

#文件上传地址
file.rootPath: E:/img/

spring:
  profiles:
    active: db
  resources:
    static-locations: file:${file.rootPath}


logging:
  level:
    com:
      wuyan:
        mall:
          mapper: debug



mybatis:
  type-handlers-package: com.wuyan.mall.mabatis

