server:
  port: 80

pagehelper:
  helper-dialect: mysql


#文件上传地址
file.rootPath: E:/img/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuyan_mall_zy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  resources:
      static-locations: file:${file.rootPath}

logging:
  level:
    com:
      wuyan:
        mall:
          mapper: debug



mybatis:
  type-handlers-package: com.wuyan.mall.mabatis


