server:
  port: 80


pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      wuyan:
        mall:
          mapper: debug
spring:
<<<<<<< HEAD
  profiles:
    active: db
=======
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuyan_mall_zy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      wuyan:
        mall:
          mapper: debug
mybatis:
  type-handlers-package: com.wuyan.mall.mybatis
>>>>>>> zydevone
