server:
  port: 80

pagehelper:
  helper-dialect: mysql

spring:
  profiles:
    active: db


logging:
  level:
    com:
      wuyan:
        mall:
          mapper: debug




mybatis:
  type-handlers-package: com.wuyan.mall.mabatis

#文件上传地址
#file.rootPath: E
#file.sonPath: /img/
